version: "3.7"
services:
  01_ui_env_a:
    build:
      context: .
    volumes:
      - /app/node_modules
      - ./src:/app/src
      - .:/app
    image: "01_ui"
    ports:
      - "3000:3000"
    environment:
      REACT_APP_ENVIRONMENT: "a"
  01_ui_env_b:
    build:
      context: .
    image: "01_ui"
    ports:
      - "3001:3000"
    environment:
      REACT_APP_ENVIRONMENT: "b"