version: "3.7"
services:
  01_ui_eu:
    build:
      context: .
    image: "01_ui"
    ports:
      - "3000:3000"
    environment:
      REACT_APP_LOCALE: "eu"
  01_ui_us:
    build:
      context: .
    image: "01_ui"
    ports:
      - "3001:3000"
    environment:
      REACT_APP_LOCALE: "us"