export const questions = [
    {
        id: 'apple',
        text_en: 'apple',
        audioId_en: 'apple_en',
        text_it: 'mela',
        audioId_it: 'mela_it',
        text_de: 'Apfel',
        audioId_de: 'Apfel_de',
        imgId: 'apple',
    },
    {
        id: 'arm',
        text_en: 'arm',
        audioId_en: 'arm_en',
        text_it: 'braccio',
        audioId_it: 'braccio_it',
        text_de: 'Arm',
        audioId_de: 'Arm_de',
        imgId: 'arm',
    },
    {
        id: 'bag',
        text_en: 'bag',
        audioId_en: 'bag_en',
        text_it: 'borsa',
        audioId_it: 'borsa_it',
        text_de: 'Tasche',
        audioId_de: 'Tasche_de',
        imgId: 'bag',
    },
    {
        id: 'ball',
        text_en: 'ball',
        audioId_en: 'ball_en',
        text_it: 'palla',
        audioId_it: 'palla_it',
        text_de: 'Ball',
        audioId_de: 'Ball_de',
        imgId: 'ball',
    },
    {
        id: 'bat',
        text_en: 'bat',
        audioId_en: 'bat_en',
        text_it: 'pipistrello',
        audioId_it: 'pipistrello_it',
        text_de: 'Schläger',
        audioId_de: 'Schläger_de',
        imgId: 'bat',
    },
    {
        id: 'bear',
        text_en: 'bear',
        audioId_en: 'bear_en',
        text_it: 'orso',
        audioId_it: 'orso_it',
        text_de: 'Bär',
        audioId_de: 'Bär_de',
        imgId: 'bear',
    },
    {
        id: 'cup',
        text_en: 'cup',
        audioId_en: 'cup_en',
        text_it: 'tazza',
        audioId_it: 'tazza_it',
        text_de: 'Tasse',
        audioId_de: 'Tasse_de',
        imgId: 'cup',
    },
    {
        id: 'car',
        text_en: 'car',
        audioId_en: 'car_en',
        text_it: 'auto',
        audioId_it: 'auto_it',
        text_de: 'Auto',
        audioId_de: 'Auto_de',
        imgId: 'car',
    },
    {
        id: 'cat',
        text_en: 'cat',
        audioId_en: 'cat_en',
        text_it: 'gatto',
        audioId_it: 'gatto_it',
        text_de: 'Katze',
        audioId_de: 'Katze_de',
        imgId: 'cat',
    },
    {
        id: 'dinosaur',
        text_en: 'dinosaur',
        audioId_en: 'dinosaur_en',
        text_it: 'dinosauro',
        audioId_it: 'dinosauro_it',
        text_de: 'Dinosaurier',
        audioId_de: 'Dinosaurier_de',
        imgId: 'dinosaur',
    },
    {
        id: 'dog',
        text_en: 'dog',
        audioId_en: 'dog_en',
        text_it: 'cane',
        audioId_it: 'cane_it',
        text_de: 'Hund',
        audioId_de: 'Hund_de',
        imgId: 'dog',
    },
    {
        id: 'elephant',
        text_en: 'elephant',
        audioId_en: 'elephant_en',
        text_it: 'elefante',
        audioId_it: 'elefante_it',
        text_de: 'Elefant',
        audioId_de: 'Elefant_de',
        imgId: 'elephant',
    },
    {
        id: 'fox',
        text_en: 'fox',
        audioId_en: 'fox_en',
        text_it: 'volpe',
        audioId_it: 'volpe_it',
        text_de: 'Fuchs',
        audioId_de: 'Fuchs_de',
        imgId: 'fox',
    },
    {
        id: 'hat',
        text_en: 'hat',
        audioId_en: 'hat_en',
        text_it: 'cappello',
        audioId_it: 'cappello_it',
        text_de: 'Hut',
        audioId_de: 'Hut_de',
        imgId: 'hat',
    },
    {
        id: 'milk',
        text_en: 'milk',
        audioId_en: 'milk_en',
        text_it: 'latte',
        audioId_it: 'latte_it',
        text_de: 'Milch',
        audioId_de: 'Milch_de',
        imgId: 'milk',
    },
    {
        id: 'robot',
        text_en: 'robot',
        audioId_en: 'robot_en',
        text_it: 'robot',
        audioId_it: 'robot_it',
        text_de: 'Roboter',
        audioId_de: 'Roboter_de',
        imgId: 'robot',
    },
    {
        id: 'snake',
        text_en: 'snake',
        audioId_en: 'snake_en',
        text_it: 'serpente',
        audioId_it: 'serpente_it',
        text_de: 'Schlange',
        audioId_de: 'Schlange_de',
        imgId: 'snake',
    },
]
